<template>
  <div
    class="solapa overflow-y-scroll w-full h-8 bg-mercury justify-center items-center overflow-y-hidden"
    :class="[state]"
  >
    <v-icon
      class="my-auto w-full"
      @click.native="toggle"
      name="chevron-up"
      scale="1.45"
    />
    <slot></slot>
  </div>
</template>

<script>
export default {
  name: 'DrawerBottom',
  data () {
    return {
      state: 'default'
    }
  },
  methods: {
    toggle () {
      if (this.state === 'default') {
        this.state = 'active'
        return
      }
      if (this.state === 'active') {
        this.state = 'inactive'
        return
      }
      if (this.state === 'inactive') {
        this.state = 'active'
        return
      }
    }
  }
}
</script>

<style scoped>
.solapa {
    position: absolute;
    margin-top: -2rem;
    border-radius: 25px 25px 0 0;
    box-shadow: 0 -1px 20px rgba(0,0,0,0.19), 0 -4px 6px rgba(0,0,0,0.23);
    height: 75%;
  }
  .active {
    -webkit-animation: slide-top 0.5s cubic-bezier(0.680, -0.550, 0.265, 1.550) both;
            animation: slide-top 0.5s cubic-bezier(0.680, -0.550, 0.265, 1.550) both;
  }
  .inactive {
    -webkit-animation: slide-bottom 0.5s cubic-bezier(0.680, -0.550, 0.265, 1.550) both;
            animation: slide-bottom 0.5s cubic-bezier(0.680, -0.550, 0.265, 1.550) both;
  }
  /* ----------------------------------------------
  * Generated by Animista on 2019-10-9 18:58:51
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info.
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */
  /**
  * ----------------------------------------
  * animation slide-top
  * ----------------------------------------
  */
  @-webkit-keyframes slide-top {
    0% {
      -webkit-transform: translateY(0);
              transform: translateY(0);
    }
    100% {
      -webkit-transform: translateY(-25rem);
              transform: translateY(-25rem);
    }
  }
  @keyframes slide-top {
    0% {
      -webkit-transform: translateY(0);
              transform: translateY(0);
    }
    100% {
      -webkit-transform: translateY(-25rem);
              transform: translateY(-25rem);
    }
  }
  @-webkit-keyframes slide-bottom {
    0% {
      -webkit-transform: translateY(-25rem);
      transform: translateY(-25rem);

    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
    }
  }
  @keyframes slide-bottom {
    0% {
      -webkit-transform: translateY(-25rem);
      transform: translateY(-25rem);

    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
    }
  }
</style>
